

server:
  port: 8070

spring:
  application:
    name: jd-consumer
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
      timeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka

feign:
  hystrix:
    enabled: false

    #hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000